backend:
  name: test-repo
  # name: git-gateway
  # branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page" }
          - { label: Title, name: title, widget: string }
          - { label: BackgroundImage, name: image, widget: image }
          - { label: Logo, name: logo, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Twitter, name: twitter, widget: string }
          - { label: Instagram, name: instagram, widget: string }
